{
 "title": "MetaX GPU",
 "description": "Display MetaX GPU metrics",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "server", "label": "server", "query": { "query": "label_values(instance)" } },
   { "name": "device", "label": "device", "query": { "query": "label_values(deviceId)" } },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Name",
   "type": "stat",
   "description": "The device name",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mx_gpu_usage{Hostname=\"$server\", deviceId=\"$device\"}"
    }
   ]
  },
  {
   "title": "Driver Version",
   "type": "stat",
   "description": "Driver Version",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mx_gpu_usage{deviceId=\"$device\", Hostname=\"$server\"}"
    }
   ]
  },
  {
   "title": "Chip Hotspot Temperature",
   "type": "gauge",
   "description": "Device chip hotspot temperature",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mx_chip_hotspot_temp{Hostname=\"$server\", deviceId=\"$device\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Board CORE Temperature",
   "type": "gauge",
   "description": "Board CORE Temperature",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mx_board_core_temp{Hostname=\"$server\", deviceId=\"$device\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "BIOS Version",
   "type": "stat",
   "description": "BIOS Version",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mx_gpu_usage{Hostname=\"$server\", deviceId=\"$device\"}"
    }
   ]
  },
  {
   "title": "BOARD POWER",
   "type": "timeseries",
   "description": "BOARD TOTAL POWER",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "mwatt" } },
   "targets": [
    {
     "expr": "mx_board_power{Hostname=\"$server\", deviceId=\"$device\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GPU Utilization",
   "type": "gauge",
   "description": "GPU Utilization",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mx_gpu_usage{Hostname=\"$server\", deviceId=\"$device\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GPU Clock",
   "type": "gauge",
   "description": "GPU Clock Frequency in MHz",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "MHz" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mx_gpu_clock{Hostname=\"$server\", deviceId=\"$device\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "VPUE Utilization",
   "type": "gauge",
   "description": "VPUE Utilization",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mx_vpue_usage{Hostname=\"$server\", deviceId=\"$device\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "VPUE Clock",
   "type": "gauge",
   "description": "VPUE Clock Frequency",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "MHz" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mx_vpue_clock{Hostname=\"$server\", deviceId=\"$device\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PCIE Speed",
   "type": "timeseries",
   "description": "PCIE current speed in GT/s",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "mx_pcie_speed{Hostname=\"$server\", deviceId=\"$device\"}"
    }
   ]
  },
  {
   "title": "VPUD Utilization",
   "type": "gauge",
   "description": "VPUD Utilization",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mx_vpud_usage{Hostname=\"$server\", deviceId=\"$device\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "VPUD Clock",
   "type": "gauge",
   "description": "VPUD Clock Frequency",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "MHz" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mx_vpud_clock{Hostname=\"$server\", deviceId=\"$device\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage - VRAM",
   "type": "gauge",
   "description": "VRAM memory usage in %",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mx_memory_usage{Hostname=\"$server\", deviceId=\"$device\", type=\"vram\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Clock",
   "type": "gauge",
   "description": "Memory Clock Frequency in MHZ",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "MHz" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mx_mem_clock{Hostname=\"$server\", deviceId=\"$device\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PCIE width",
   "type": "timeseries",
   "description": "PCIE current lanes",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "mx_pcie_width{Hostname=\"$server\", deviceId=\"$device\"}"
    }
   ]
  },
  {
   "title": "DPM Xcore",
   "type": "timeseries",
   "description": "DPM xcore performance level",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "mx_xcore_dpm_level{Hostname=\"$server\", deviceId=\"$device\"}"
    }
   ]
  },
  {
   "title": "PCIE Bridge Speed",
   "type": "timeseries",
   "description": "PCIE bridge current speed in GT/s",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "mx_pcie_bridge_speed{Hostname=\"$server\", deviceId=\"$device\"}"
    }
   ]
  },
  {
   "title": "MetaXLink traffic average transmit rate (Bytes/sec)",
   "type": "timeseries",
   "description": "MetaXLink traffic average  transmit rate (Bytes/sec)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(mx_mxlk_traffic_total_bytes{Hostname=\"$server\", deviceId=\"$device\", type=\"tx\"}[$__rate_interval])",
     "legendFormat": "MetaXLink-{{mxlkId}}"
    }
   ]
  },
  {
   "title": "PCIE Bridge width",
   "type": "timeseries",
   "description": "PCIE bridge current lanes",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "targets": [
    {
     "expr": "mx_pcie_bridge_width{Hostname=\"$server\", deviceId=\"$device\"}"
    }
   ]
  },
  {
   "title": "MetaXLink traffic average receive rate (Bytes/sec)",
   "type": "timeseries",
   "description": "MetaXLink traffic average receive rate (Bytes/sec)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(mx_mxlk_traffic_total_bytes{Hostname=\"$server\", deviceId=\"$device\", type=\"rx\"}[$__rate_interval])",
     "legendFormat": "MetaXLink-{{mxlkId}}"
    }
   ]
  },
  {
   "title": "MetaXLink Speed GT/s",
   "type": "table",
   "description": "MetaXLink Speed GT/s",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 47 },
   "targets": [
    {
     "expr": "mx_mxlk_speed{Hostname=\"$server\", deviceId=\"$device\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Driver EID Errors",
   "type": "table",
   "description": "Display Driver EID Error.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "hex0x" } },
   "targets": [
    {
     "expr": "mx_driver_eid_errors{Hostname=\"$server\", deviceId=\"$device\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MetaXLink current link width",
   "type": "table",
   "description": "MetaXLink current link width",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 52 },
   "targets": [
    {
     "expr": "mx_mxlk_width{Hostname=\"$server\", deviceId=\"$device\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MetaXLink aer count",
   "type": "timeseries",
   "description": "MetaXLink aer count, including ce(correctable error) and ue(uncorrectable error)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
   "targets": [
    {
     "expr": "mx_mxlk_aer_count{Hostname=\"$server\", deviceId=\"$device\", type=\"ce\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "mx_mxlk_aer_count{Hostname=\"$server\", deviceId=\"$device\", type=\"ue\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SDK EID Errors",
   "type": "table",
   "description": "Display SDK EID Error.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "hex0x" } },
   "targets": [
    {
     "expr": "mx_sdk_eid_errors{Hostname=\"$server\", deviceId=\"$device\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PCIe Throughput",
   "type": "timeseries",
   "description": " PCIe throughput, label type indicates tx or rx",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 65 },
   "targets": [
    {
     "expr": "mx_pcie_bw{Hostname=\"$server\", deviceId=\"$device\", type=\"rx\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "mx_pcie_bw{Hostname=\"$server\", deviceId=\"$device\", type=\"tx\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Driver pci event ",
   "type": "timeseries",
   "description": "Driver pci event includes aer_ue/aer_ce/synfld/dbe/mmio",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "hex0x" } },
   "targets": [
    {
     "expr": "mx_pci_event{Hostname=\"$server\", deviceId=\"$device\", type=\"aer_ce\"}",
     "legendFormat": "{{event_name}}"
    },
    {
     "expr": "mx_pci_event{Hostname=\"$server\", deviceId=\"$device\", type=\"aer_ue\"}",
     "legendFormat": "{{event_name}}"
    }
   ]
  },
  {
   "title": "MetaxLink Throughput",
   "type": "timeseries",
   "description": "MetaxLink throughput, label type indicates tx or rx",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 73 },
   "targets": [
    {
     "expr": "mx_mxlk_bw{Hostname=\"$server\", deviceId=\"$device\", type=\"rx\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "mx_mxlk_bw{Hostname=\"$server\", deviceId=\"$device\", type=\"tx\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ecc error counts",
   "type": "timeseries",
   "description": "Label type indicates sram_ce, sram_ue, dram_ce, dram_ue or retired_page",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 73 },
   "targets": [
    {
     "expr": "mx_ecc_error_count{Hostname=\"$server\", deviceId=\"$device\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GPU unavailable reason",
   "type": "stat",
   "description": " Show gpu unavailable reason if GPU not available",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mx_gpu_state{Hostname=\"$server\", deviceId=\"$device\",unavailable_reason!=\"\"}",
     "legendFormat": "{{unavailable_reason}}"
    }
   ]
  },
  {
   "title": "Clock Throttling",
   "type": "stat",
   "description": "current gpu clock throttle reason, 0 means no clock throttling happen. There are total 9 reasons, you need to change the value from DEC to BIN, and from low to high are reasons: Idle，Application Limit，Over Power，Chip Over Temperature，VR Over Temperature，HBM Over Temperature，Thermal Over Temperature，PCC，Power Brake，DIDT，Low Usage，Other. Or you may meet multiple reasons.                                                                                                                                                                                                                                                                                                                                                                                                   ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 81 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mx_clk_thr{Hostname=\"$server\", deviceId=\"$device\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ras Error Count",
   "type": "stat",
   "description": "Display value in the ras error counter registers",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 89 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mx_ras_count{Hostname=\"$server\", deviceId=\"$device\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}