{
 "title": "sGPU",
 "time": { "from": "2025-04-10T08:15:45.527Z", "to": "2025-04-10T13:06:19.867Z" },
 "templating": {
  "list": [
   {
    "name": "hostname",
    "query": {
     "query": "label_values(mx_sgpu_usage,Hostname)"
    }
   },
   {
    "name": "gpu",
    "query": {
     "query": "label_values(mx_sgpu_usage{Hostname=~\"$hostname\"},deviceId)"
    }
   },
   {
    "name": "sgpu",
    "query": {
     "query": "label_values(mx_sgpu_usage{Hostname=~\"$hostname\", deviceId=~\"$gpu\"},sgpuId)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Quota",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "mx_sgpu_compute_quota{Hostname=~\"$hostname\", deviceId=~\"$gpu\", sgpuId=~\"$sgpu\"}",
     "legendFormat": "{{Hostname}} | {{deviceId}} | {{sgpuId}} | {{uuid}}"
    }
   ]
  },
  {
   "title": "sGPU usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "mx_sgpu_usage{Hostname=~\"$hostname\", deviceId=~\"$gpu\", sgpuId=~\"$sgpu\"}",
     "legendFormat": "{{Hostname}} | {{deviceId}} | {{sgpuId}} | {{uuid}}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "mx_sgpu_used_memory{Hostname=~\"$hostname\", deviceId=~\"$gpu\", sgpuId=~\"$sgpu\"} / mx_sgpu_total_memory{Hostname=~\"$hostname\", deviceId=~\"$gpu\", sgpuId=~\"$sgpu\"}",
     "legendFormat": "{{Hostname}} | {{deviceId}} | {{sgpuId}} | {{uuid}}"
    }
   ]
  }
 ]
}